valor = input('Digite algo: ')
print('O tipo primitivo do que você digitou é uma', type(valor))
print('É alfanumérico?', valor.isalnum())
print('É alfabético?', valor.isalpha())
print('É numérico?', valor.isnumeric())
print('Só tem espaços?', valor.isspace())
print('São apenas letras minúsculas?', valor.islower())
print('São apenas letras maiúsculas?', valor.isupper())
print('Esta capitalizada?', valor.istitle())
print('São dígitos?', valor.isdigit())